light.dining_room_level_5_0:
  refresh_value: true
  delay: 2
light.living_room_level_6_0:
  refresh_value: true
  delay: 2
binary_sensor.front_door_sensor_8_0:
  ignored: false
  polling_intensity: 0
