- platform: garadget
  covers:
    45001d001151353432393433:
      username: !secret garadget_username
      password: !secret garadget_password
      name: Main Garage Door
    1e0037000251353530353431:
      username: !secret garadget_username
      password: !secret garadget_password
      name: Small Garage Door