- platform: template
  sensors:
    main_garage_door_status:
      friendly_name: 'State of the door'
      value_template: '{{ states.cover.main_garage_door.state }}'
    main_garage_door_time_in_state:
      friendly_name: 'Since'
      value_template: '{{ states.cover.main_garage_door.attributes["time in state"] }}'
    main_garage_door_wifi_signal_strength:
      friendly_name: 'WiFi strength'
      value_template: '{{ states.cover.main_garage_door.attributes["wifi signal strength (dB)"] }}'
      unit_of_measurement: 'dB'
    main_garage_door_reflection_rate:
      friendly_name: 'Reflection Rate'
      value_template: '{{ states.cover.main_garage_door.attributes["sensor reflection rate"] }}'
    # small_garage_door_status:
    #   friendly_name: 'State of the door'
    #   value_template: '{{ states.cover.small_garage_door.state }}'
    # small_garage_door_time_in_state:
    #   friendly_name: 'Since'
    #   value_template: '{{ states.cover.small_garage_door.attributes["time in state"] }}'
    # small_garage_door_wifi_signal_strength:
    #   friendly_name: 'WiFi strength'
    #   value_template: '{{ states.cover.small_garage_door.attributes["wifi signal strength (dB)"] }}'
    #   unit_of_measurement: 'dB'
    # small_garage_door_reflection_rate:
    #   friendly_name: 'Reflection Rate'
    #   value_template: '{{ states.cover.small_garage_door.attributes["sensor reflection rate"] }}'