- alias: Amanda Left
  trigger:
    platform: zone
    entity_id: device_tracker.paolo_nexus5x
    zone: zone.home
    event: leave
  action:
    service: notify.hassbot
    data:
      message: "Amanda left the house"
- alias: Amanda Back
  trigger:
    platform: zone
    entity_id: device_tracker.paolo_nexus5x
    zone: zone.home
    event: enter
  action:
    service: notify.hassbot
    data:
      message: "Amanda has arrived at the house"
- alias: Paolo Left
  trigger:
    platform: zone
    entity_id: device_tracker.paolo_nexus6p
    zone: zone.home
    event: leave
  action:
    service: notify.hassbot
    data:
      message: "Paolo left the house"
- alias: Paolo Back
  trigger:
    platform: zone
    entity_id: device_tracker.paolo_nexus6p
    zone: zone.home
    event: enter
  action:
    service: notify.hassbot
    data:
      message: "Paolo has arrived at the house"